### ISSUE TITLE
 Allowed memory size of XXX bytes exhausted

### ISSUE THREAD

**Issue by acvegab** [verkhoumov/codeigniter-mongodb-library#23]
Hi, the library doesn't support collections with hundred thousands of documents.

( ! ) Fatal error: Allowed memory size of XXXXX bytes exhausted (tried to allocate XXX bytes) in application/librariesMongo_db.php on line 2515

Adding a limit to my query was my solution, but I wanted to mention it here, maybe something can be done direct in the library.

**Comment by apartamenti** [comment]
Try to change your php settings.

ini_set('memory_limit', '-1');

**Comment by verkhoumov** [comment]
Dear @acvegab, the problem is really related to a lack of memory. Obtaining this amount of data is a serious mistake on your part. So you not only load the handler, but the database itself. I strongly recommend that you use this amounts of data in batches. If possible, refuse to manipulate such a large amount of data at the same time and consider the possibility of processing by several approaches.

**Comment by acvegab** [comment]
Thank you, I never had problems with other mongo libraries but my query wasn't very efficient, so I fixed it  and now It's working great.
